# Generated by Django 4.1.7 on 2023-03-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slud',
            new_name='slug',
        ),
    ]
